name: Test CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Test-Pipeline:
    runs-on: ubuntu-latest
    
    steps:
      # Langkah 1: Melakukan checkout kode
      - name: Checkout code
        uses: actions/checkout@v4

      # Langkah 2: Menjalankan echo dan mencetak secret
      - name: Print Pipeline Status and Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET_KEY }}
        run: |
          echo "Pipeline Berjalan!"
          echo "Secret Key: $MY_SECRET"
